### ISSUE TITLE
css is not working 

### ISSUE THREAD

**Issue by ShridharAggrwal** [Polaris-School-of-Technology/bill-splitter--pst#2]
in the bill splitter we do not have css conneted also images are not vissible

**Comment by ShridharAggrwal** [comment]
![Screenshot 2024-12-06 164121](https://github.com/user-attachments/assets/45188667-4394-45fa-83b4-a69206cf9027)

**Comment by Akhilesh-max** [comment]
This issue is not valid. See #4
