### ISSUE TITLE
index.js file is missing

### ISSUE THREAD

**Issue by Nivedita-Chhokar** [Polaris-School-of-Technology/bill-splitter--pst#3]
The project appears to be missing the `index.js` file, which is crucial for the setup and execution of the application. This absence is causing the application to fail at startup, as there is no JavaScript entry point.

**Comment by Nivedita-Chhokar** [comment]
I would like to be assigned to this issue to help resolve it.

**Comment by ShridharAggrwal** [comment]
index.html is there in the bill-splitter--pst\money_splitter\templates\splitter\index.html

**Comment by Akhilesh-max** [comment]
This issue is not valid. There would be some other file to initiate the execution.
