### ISSUE TITLE
The UI of the money splitter is not so interactive 

### ISSUE THREAD

**Issue by SOHAMPAL23** [Polaris-School-of-Technology/bill-splitter--pst#4]
when we are using the money splitter which is not having a good UI it is not interactive not easy to understand  so i have created a more easy and interactive and dark mode is included in it 
![image](https://github.com/user-attachments/assets/6ea744d4-6905-4e87-a63b-e1d7133571d9)
![WhatsApp Image 2024-11-29 at 22 38 41_458492be](https://github.com/user-attachments/assets/0291985a-3318-4ae2-bd1c-0f12eb73031d)
![WhatsApp Image 2024-11-29 at 22 38 23_eb0ca502](https://github.com/user-attachments/assets/8b8a4f1b-2da4-4702-95fa-88fdfa7138f5)

**Comment by SOHAMPAL23** [comment]
It is more optimized  then before 
it it easy to understand

**Comment by Akhilesh-max** [comment]
@SOHAMPAL23, The first thing we do on Issue tab, is listing the issue properly. Do that please (Deliberation over the solution and solution modeling will come next.).
If you think, the UI is inadequate, highlight is properly with reasonable points.
